name: github flow
on: push

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
      - name: print hello world
        run: echo "Hello techie"

      - name: clone repo with java
        uses: actions/checkout@v4
      
      - name: set-up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
        
      - name: print java file
        run: java javafile.java

      - name: send mail using ci/cd
        if: ${{ always() }}
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.gmail.com
          port: 465
          account: ${{secrets.MAIL_ADDRESS}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: Bharathvaj
          from: ${{secrets.MAIL_ADDRESS}}
          to: bharathvajt.it2020@gmail.com
          subject: ${{github.job}} job of ${{github.repository}} has ${{job.status}}
          body: ${{github.job}} job in workflow ${{github.workflow}} of ${{github.repository}} has ${{job.status}}
          # # Optional content type (defaults to text/plain)
          # contentType: text/plain
          # # Optional attachment files (JSON type. require property 'path')
          # attachments: '[{"path":"README.md"}]'