name: github flow
on: push

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
      - name: print hello world
        run: echo "Hello techie"

      - name: clone repo with java
        uses: actions/checkout@v4
      
      - name: set-up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
        
      - name: print java file
        run: java javafile.java

      - name: send mail using ci/cd
        if: ${{ always() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465

          username: ${{secrets.MAIL_ADDRESS}}
          password: ${{secrets.MAIL_PASSWORD}}

          subject: ${{github.job}} job of ${{github.repository}} has ${{job.status}}
          body: ${{github.job}} job in workflow ${{github.workflow}} of ${{github.repository}} has ${{job.status}}

          to: bharathvajt.it2020@gmail.com
          from: ${{secrets.MAIL_ADDRESS}}

          # # Optional content type (defaults to text/plain)
          # contentType: text/plain
          # # Optional attachment files (JSON type. require property 'path')
          attachments: '[{"path":"README.md"}]'